---
name: Test-CheckChanges
version: 0.10
author:
  - '"G. Allen Morris III" <gam3@gam3.net>'
abstract: Check that the Changes file matches the distribution.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  perl: 5.006
recommends:
  Module::Build: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Test::CheckChanges:
    file: lib/Test/CheckChanges.pm
    version: 0.10
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
